data_root: data

data_ingestion:
  root_dir: data/data_ingestion
  local_data_file: /home/kubuntu/Desktop/my_pc/archive.zip
  unzip_dir: data/data_ingestion

artifacts_root: artifacts
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5